apiVersion: apps/v1
kind: Deployment
metadata:
  namespace : fyc-ek 
  name: kibana
  labels:
    name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kibana
  template:
    metadata:
      labels:
          name: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:6.8.0
          ports:
            - containerPort: 5601
              name: http
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200/
---
apiVersion: v1
kind: Service
metadata:
  namespace : fyc-ek 
  name: kibana
  labels:
    name: kibana
spec:
  selector:
    name: kibana
  type: LoadBalancer
  ports:
    - nodePort: 
      port: 5601
      protocol: TCP
      targetPort: 5601