version: '3'
services:
  app-vote-back:
    image: redis:6.0.8
    container_name: app-vote-back
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "6379:6379"


  app-vote-front:
    build: ./app-vote
    image: vote-front:v1
    container_name: app-vote-front
    environment:
      REDIS: app-vote-back
    ports:
        - "8080:80"
    volumes:
      - /data/:/data/logs/:rw